day_start_time:
  name: Day Start Time
  has_time: true
  has_date: false
  initial: "05:30"

office_early_work_mode_day_start_time:
  name: Tina Office Early Work Mode Day Start Time
  has_time: true
  has_date: false
  initial: "03:00:00"

night_start_time:
  name: Night Start Time
  has_time: true
  has_date: false
  initial: "21:00"

office_apply_occupied_start_time:
  name: Tina Office Apply Occupied Start Time
  has_time: true
  has_date: false
  initial: "09:00:00"

office_apply_occupied_end_time:
  name: Tina Office Apply Occupied End Time
  has_time: true
  has_date: false
  initial: "20:59:00"

family_room_apply_occupied_start_time:
  name: Family Room Apply Occupied Start Time
  has_time: true
  has_date: false
  initial: "09:00:00"

family_room_apply_occupied_end_time:
  name: Family Room Apply Occupied End Time
  has_time: true
  has_date: false
  initial: "20:59:00"

