# Loads default set of integrations. Do not remove.
default_config:

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

automation: !include_dir_merge_list automations/
script: !include scripts.yaml
scene: !include scenes.yaml

notify:
  - name: file
    platform: file
    filename: "/config/notifications.log"

input_boolean: !include_dir_merge_named input_boolean/
input_datetime: !include_dir_merge_named input_datetime/
input_select: !include_dir_merge_named input_select/
input_number: !include_dir_merge_named input_number/
input_text: !include_dir_merge_named input_text/
rest: !include_dir_merge_named rest/
timer: !include_dir_merge_named timers/
template:
  - sensor: !include_dir_merge_list template/sensor/
  - binary_sensor: !include_dir_merge_list template/binary_sensor/
scripts: !include_dir_merge_named scripts/

sensor: !include_dir_merge_list sensors/
