# Loads default set of integrations. Do not remove.
default_config:

# HTTP configuration for reverse proxy
http:
  use_x_forwarded_for: true
  trusted_proxies:
    - 192.168.0.0/16     # All local network addresses
    - 172.16.0.0/12      # Docker networks
    - 10.0.0.0/8         # More private networks
    - 127.0.0.1          # Localhost
    - ::1                # IPv6 localhost
    - 100.64.0.0/10      # Tailscale CGNAT range
    - fd7a:115c:a1e0::/48 # Tailscale IPv6 range

homeassistant:
  name: Home
  latitude: 42.24953
  longitude: -71.06616
  elevation: 20
  radius: 100
  unit_system: imperial
  currency: USD
  country: US
  time_zone: "America/New_York"

  allowlist_external_dirs:
    - "/config/"
    - "/config/snapshots/"
    - "/config/www/"

  debug: false

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

automation: !include_dir_merge_list automations/
script: !include_dir_merge_named scripts/
scene: !include scenes.yaml
utility_meter: !include_dir_merge_named utility_meters/

logger:
  default: warning
  logs:
    homeassistant.components.file: debug

notify:
  - name: file
    platform: file
    filename: "/config/notifications.log"
  - name: snapshot_log
    platform: file
    filename: "/config/snapshots/snapshot_hourly_data.json"


input_boolean: !include_dir_merge_named input_boolean/
input_datetime: !include_dir_merge_named input_datetime/
input_select: !include_dir_merge_named input_select/
input_number: !include_dir_merge_named input_number/
input_text: !include_dir_merge_named input_text/
rest: !include_dir_merge_named rest/
timer: !include_dir_merge_named timers/
template:
  - sensor: !include_dir_merge_list template/sensor/
  - binary_sensor: !include_dir_merge_list template/binary_sensor/

sensor: !include_dir_merge_list sensors/
shell_command: !include_dir_merge_named shell_command/

python_script:

# InfluxDB 2.x Configuration
influxdb:
  api_version: 2
  ssl: false
  host: docker-services-host.lan
  port: 8087
  token: "BNH25bkqKoHuSHm5Rmh4fgiMFqs7QfrCHWGzqBXDpks2pd7G"
  organization: "homelab"
  bucket: "home_assistant"
  tags:
    source: home_assistant
  tags_attributes:
    - friendly_name
  default_measurement: state
  # Include all sensors, binary sensors, and HVAC input_numbers
  include:
    domains:
      - sensor
      - binary_sensor
    entity_globs:
      - "input_number.hvac_*"
  # Exclude all other domains
  exclude:
    domains:
      - automation
      - button
      - camera
      - climate
      - cover
      - device_tracker
      - fan
      - group
      - humidifier
      - input_boolean
      - input_button
      - input_datetime
      - input_number
      - input_select
      - input_text
      - light
      - lock
      - media_player
      - number
      - person
      - remote
      - scene
      - script
      - select
      - siren
      - sun
      - switch
      - timer
      - update
      - vacuum
      - water_heater
      - weather
      - zone