# Loads default set of integrations. Do not remove.
default_config:


homeassistant:
  name: Home
  latitude: 42.24953
  longitude: -71.06616
  elevation: 20
  radius: 100
  unit_system: imperial
  currency: USD
  country: US
  time_zone: "America/New_York"

  allowlist_external_dirs:
    - "/config/"
    - "/config/snapshots/"
    - "/config/www/"

  debug: false

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

automation: !include_dir_merge_list automations/
script: !include_dir_merge_named scripts/
scene: !include scenes.yaml
utility_meter: !include_dir_merge_named utility_meters/

logger:
  default: warning
  logs:
    homeassistant.components.file: debug

notify:
  - name: file
    platform: file
    filename: "/config/notifications.log"
  - name: snapshot_log
    platform: file
    filename: "/config/snapshots/snapshot_hourly_data.json"


input_boolean: !include_dir_merge_named input_boolean/
input_datetime: !include_dir_merge_named input_datetime/
input_select: !include_dir_merge_named input_select/
input_number: !include_dir_merge_named input_number/
input_text: !include_dir_merge_named input_text/
rest: !include_dir_merge_named rest/
timer: !include_dir_merge_named timers/
template:
  - sensor: !include_dir_merge_list template/sensor/
  - binary_sensor: !include_dir_merge_list template/binary_sensor/

sensor: !include_dir_merge_list sensors/

python_script: