default_config:
frontend:
  themes: !include_dir_merge_named themes
automation: !include_dir_merge_list automations/
script: !include scripts.yaml
scene: !include scenes.yaml
input_datetime: !include_dir_merge_named input_datetime/
input_select: !include_dir_merge_named input_select/
input_number: !include_dir_merge_named input_number/
template:
  - sensor: !include_dir_merge_named template/sensor/
  - binary_sensor: !include_dir_merge_named template/binary_sensor/
sensor: !include_dir_merge_list sensor/
