day_of_week_status:
  name: Day of Week Status
  options:
    - "Weekend"
    - "Weekday"
  initial: "Weekday"

heatpump_room_tab:
  name: Heat Pump Room Tabs
  options:
    - "Office"
    - "Family Room"
    - "Living Room"
    - "Master Bedroom"
    - "Dining Room"
    - "Erik Office"
    - "Ducted"
    - "Main Heat Zone"
    - "Settings"
  initial: "Office"
  icon: mdi:home-group

