# General mode
hvac_away_mode:
  name: HVAC Away/Vacation Mode
  initial: off
  icon: mdi:airplane

# Office Radiator
hvac_away_radiator_on_office:
  name: HVAC Away Office Radiator On
  initial: on
  icon: mdi:radiator

# Office Mini Split
hvac_away_mini_split_on_office:
  name: HVAC Away Office Mini Split On
  initial: off
  icon: mdi:radiator

# Family Room Radiator
hvac_away_radiator_on_family_room:
  name: HVAC Away Family Room Radiator On
  initial: on
  icon: mdi:radiator

# Family Room Mini Split
hvac_away_mini_split_on_family_room:
  name: HVAC Away Family Room Mini Split On
  initial: off
  icon: mdi:radiator

# Main Zone Radiators
hvac_away_radiator_on_main_zone:
  name: HVAC Away Main Zone Radiators On
  initial: on
  icon: mdi:radiator

# Living Room Mini Split
hvac_away_mini_split_on_living_room:
  name: HVAC Away Living Room Mini Split On
  initial: off
  icon: mdi:radiator

# Dining Room Mini Split
hvac_away_mini_split_on_dining_room:
  name: HVAC Away Dining Room Mini Split On
  initial: off
  icon: mdi:radiator

# Erik Office Mini Split
hvac_away_mini_split_on_erik_office:
  name: HVAC Away Erik Office Mini Split On
  initial: off
  icon: mdi:radiator

# Master Bedroom Mini Split
hvac_away_mini_split_on_master_bedroom:
  name: HVAC Away Master Bedroom Mini Split On
  initial: off
  icon: mdi:radiator

# Ducted System
hvac_away_system_on_ducted:
  name: HVAC Away Ducted System On
  initial: off
  icon: mdi:radiator

# Main Radiator Zone
hvac_away_radiator_on_main_radiator_zone:
  name: HVAC Away Main Radiator Zone On
  initial: on
  icon: mdi:radiator