- platform: history_stats
  name: "HVAC Heat Called For In Last Hour Office"
  entity_id: binary_sensor.hvac_radiator_calling_for_heat_office
  state: 'on'
  type: count
  start: "{{ now() - timedelta(hours=1) }}"
  end: "{{ now() }}"

- platform: history_stats
  name: "HVAC Heat Called For In Last Hour Family Room"
  entity_id: binary_sensor.hvac_radiator_calling_for_heat_family_room
  state: 'on'
  type: count
  start: "{{ now() - timedelta(hours=1) }}"
  end: "{{ now() }}"

- platform: history_stats
  name: "HVAC Heat Called For In Last Hour Living Room"
  entity_id: binary_sensor.hvac_radiator_calling_for_heat_living_room
  state: 'on'
  type: count
  start: "{{ now() - timedelta(hours=1) }}"
  end: "{{ now() }}"