- name: "Daytime Status"
  unique_id: daytime_status
  state: >
    {% set mode = states('input_select.day_night_mode') %}
    {% set today = now().date() %}
    {% set day_start = today ~ ' ' ~ states('input_datetime.day_start_time') %}
    {% set night_start = today ~ ' ' ~ states('input_datetime.night_start_time') %}
    {% set day_start_ts = as_timestamp(day_start) %}
    {% set night_start_ts = as_timestamp(night_start) %}
    {% set now_ts = now().timestamp() %}

    {% if mode == 'Day' %}
        true
    {% elif mode == 'Night' %}
        false
    {% else %}
        {{ day_start_ts <= now_ts < night_start_ts }}
    {% endif %}
