- name: "Kids Rooms Need Heat"
  unique_id: kids_rooms_need_heat
  state: >
    {% set current_temp = states('sensor.kids_rooms_average_temperature') | float(66) %}
    {% set time_period = states('sensor.ducted_time_period') %}
    {% set trigger_offset = states('input_number.ducted_setpoint_heat_trigger_threshold_offset') | float(66) %}
    {% set stop_offset = states('input_number.ducted_setpoint_heat_stop_threshold_offset') | float(66) %}
    {% set supplemental_mode = is_state('sensor.ducted_heat_pump_operational_mode', 'Supplemental Heat') %}
    {% set target_temp = {
      'Daytime': states('input_number.ducted_heatpump_supplemental_heat_kids_rooms_daytime_target') | float(66) if supplemental_mode else states('input_number.ducted_heatpump_kids_rooms_daytime_target') | float(66),
      'Bedtime': states('input_number.ducted_heatpump_supplemental_heat_kids_rooms_bedtime_target') | float(66) if supplemental_mode else states('input_number.ducted_heatpump_kids_rooms_bedtime_target') | float(66),
      'Sleep': states('input_number.ducted_heatpump_supplemental_heat_kids_rooms_sleep_target') | float(66) if supplemental_mode else states('input_number.ducted_heatpump_kids_rooms_sleep_target') | float(66)
    }.get(time_period, 66) %}
    {% set is_heating = is_state('binary_sensor.kids_rooms_need_heat', 'on') %}
    {{ current_temp < (target_temp - trigger_offset) if not is_heating else current_temp < (target_temp + stop_offset) }}
  icon: >-
    {% if is_state('binary_sensor.kids_rooms_need_heat', 'on') %}
      mdi:thermometer-alert
    {% else %}
      mdi:thermometer
    {% endif %}

- name: "Stairwell Needs Heat"
  unique_id: stairwell_need_heat
  state: >
    {% set current_temp = states('sensor.stairwell_average_temperature') | float(66) %}
    {% set time_period = states('sensor.ducted_time_period') %}
    {% set trigger_offset = states('input_number.ducted_setpoint_heat_trigger_threshold_offset') | float(66) %}
    {% set stop_offset = states('input_number.ducted_setpoint_heat_stop_threshold_offset') | float(66) %}
    {% set supplemental_mode = is_state('sensor.ducted_heat_pump_operational_mode', 'Supplemental Heat') %}
    {% set target_temp = {
      'Daytime': states('input_number.ducted_heatpump_supplemental_heat_stairwell_daytime_target') | float(66) if supplemental_mode else states('input_number.ducted_heatpump_stairwell_daytime_target') | float(66),
      'Bedtime': states('input_number.ducted_heatpump_supplemental_heat_stairwell_bedtime_target') | float(66) if supplemental_mode else states('input_number.ducted_heatpump_stairwell_bedtime_target') | float(66),
      'Sleep': states('input_number.ducted_heatpump_supplemental_heat_stairwell_sleep_target') | float(66) if supplemental_mode else states('input_number.ducted_heatpump_stairwell_sleep_target') | float(66)
    }.get(time_period, 66) %}
    {% set is_heating = is_state('binary_sensor.stairwell_need_heat', 'on') %}
    {{ current_temp < (target_temp - trigger_offset) if not is_heating else current_temp < (target_temp + stop_offset) }}
  icon: >-
    {% if is_state('binary_sensor.stairwell_need_heat', 'on') %}
      mdi:thermometer-alert
    {% else %}
      mdi:thermometer
    {% endif %}