- platform: history_stats
  unique_id: office_occupancy_detected_last_hour
  name: "Office Occupancy Detected Last Hour"
  entity_id: binary_sensor.office_occupancy_detected
  state: "on"
  type: count
  duration:
    minutes: 60
  end: "{{ now() }}"

- platform: history_stats
  unique_id: family_room_occupancy_detected_last_hour
  name: "Family Room Occupancy Detected Last Hour"
  entity_id: binary_sensor.family_room_occupancy_detected
  state: "on"
  type: count
  duration:
    minutes: 60
  end: "{{ now() }}"

- platform: history_stats
  unique_id: living_room_occupancy_detected_last_hour
  name: "Living Room Occupancy Detected Last Hour"
  entity_id: binary_sensor.living_room_occupancy_detected
  state: "on"
  type: count
  duration:
    minutes: 60
  end: "{{ now() }}"

- platform: history_stats
  unique_id: dining_room_occupancy_detected_last_hour
  name: "Dining Room Occupancy Detected Last Hour"
  entity_id: binary_sensor.dining_room_occupancy_detected
  state: "on"
  type: count
  duration:
    minutes: 60
  end: "{{ now() }}"

- platform: history_stats
  unique_id: kitchen_occupancy_detected_last_hour
  name: "Kitchen Occupancy Detected Last Hour"
  entity_id: binary_sensor.kitchen_occupancy_detected
  state: "on"
  type: count
  duration:
    minutes: 60
  end: "{{ now() }}"

- platform: history_stats
  unique_id: master_bedroom_occupancy_detected_last_hour
  name: "Master Bedroom Occupancy Detected Last Hour"
  entity_id: binary_sensor.master_bedroom_occupancy_detected
  state: "on"
  type: count
  duration:
    minutes: 60
  end: "{{ now() }}"

- platform: history_stats
  unique_id: tillys_room_occupancy_detected_last_hour
  name: "Tilly's Room Occupancy Detected Last Hour"
  entity_id: binary_sensor.tilly_s_room_occupancy_detected
  state: "on"
  type: count
  duration:
    minutes: 60
  end: "{{ now() }}"

- platform: history_stats
  unique_id: hanks_room_occupancy_detected_last_hour
  name: "Hank's Room Occupancy Detected Last Hour"
  entity_id: binary_sensor.hank_s_room_occupancy_detected
  state: "on"
  type: count
  duration:
    minutes: 60
  end: "{{ now() }}"
