dining_room_heatpump_off_to_supplement_threshold:
  name: Dining Room Heat Pump Off Temp
  min: -15
  max: 60
  step: 1
  unit_of_measurement: "째F"
  initial: -13

dining_room_heatpump_supplement_to_comfort_threshold:
  name: Dining Room Heat Pump Comfort Temp
  min: -15
  max: 60
  step: 1
  unit_of_measurement: "째F"
  initial: -10

dining_room_overheated_threshold:
  name: Dining Room Overheat Threshold
  min: 70
  max: 90
  step: 1
  unit_of_measurement: "째F"
  initial: 74

dining_room_override_setpoint:
  name: Dining Room Override Temperature
  min: 60
  max: 80
  step: 1
  unit_of_measurement: "째F"
  initial: 70

dining_room_override_for_hours:
  name: Dining Room Override For Hours
  min: 0.5
  max: 24
  step: 0.5
  unit_of_measurement: "hours"
  initial: 2