erik_office_heatpump_off_to_supplement_threshold:
  name: Erik Office Heat Pump Off Temp
  min: -15
  max: 60
  step: 1
  unit_of_measurement: "째F"
  initial: 22

erik_office_heatpump_supplement_to_comfort_threshold:
  name: Erik Office Heat Pump Comfort Temp
  min: -15
  max: 60
  step: 1
  unit_of_measurement: "째F"
  initial: 32

erik_office_overheated_threshold:
  name: Erik Office Overheat Threshold
  min: 70
  max: 90
  step: 1
  unit_of_measurement: "째F"
  initial: 73

erik_office_override_setpoint:
  name: Erik Office Override Temperature
  min: 60
  max: 80
  step: 1
  unit_of_measurement: "째F"
  initial: 70

erik_office_override_for_hours:
  name: Erik Office Override For Hours
  min: 0.5
  max: 24
  step: 0.5
  unit_of_measurement: "hours"
  initial: 2