family_room_heatpump_off_to_supplement_threshold:
  name: Family Room Heat Pump Off Temp
  min: -15
  max: 60
  step: 1
  unit_of_measurement: "째F"
  initial: 33

family_room_heatpump_supplement_to_comfort_threshold:
  name: Family Room Heat Pump Comfort Temp
  min: -15
  max: 60
  step: 1
  unit_of_measurement: "째F"
  initial: 39

family_room_overheated_threshold:
  name: Family Room Overheat Threshold
  min: 70
  max: 90
  step: 1
  unit_of_measurement: "째F"
  initial: 73

family_room_override_setpoint:
  name: Family Room Override Temperature
  min: 60
  max: 80
  step: 1
  unit_of_measurement: "째F"
  initial: 70

family_room_override_for_hours:
  name: Family Room Override For Hours
  min: 0.5
  max: 24
  step: 0.5
  unit_of_measurement: "hours"
  initial: 2