living_room_heatpump_off_to_supplement_threshold:
  name: Living Room Heat Pump Off Temp
  min: -15
  max: 60
  step: 1
  unit_of_measurement: "°F"
  initial: 22

living_room_heatpump_supplement_to_comfort_threshold:
  name: Living Room Heat Pump Comfort Temp
  min: -15
  max: 60
  step: 1
  unit_of_measurement: "°F"
  initial: 40

living_room_heatpump_boost_off_threshold:
  name: Living Room Boost Off Temp
  min: -15
  max: 60
  step: 1
  unit_of_measurement: "°F"
  initial: 22

living_room_overheated_threshold:
  name: Living Room Overheat Threshold
  min: 70
  max: 90
  step: 1
  unit_of_measurement: "°F"
  initial: 73

living_room_override_setpoint:
  name: Living Room Override Temperature
  min: 60
  max: 80
  step: 1
  unit_of_measurement: "°F"
  initial: 70

living_room_override_for_hours:
  name: Living Room Override For Hours
  min: 0.5
  max: 24
  step: 0.5
  unit_of_measurement: "hours"
  initial: 2

living_room_boost_target:
  name: Living Room Boost Mode Heating Temperature
  min: 64
  max: 80
  step: 1
  unit_of_measurement: "°F"
  initial: 72

living_room_boost_setpoint_heat_trigger_threshold_offset:
  name: Living Room Boost Heat Trigger Threshold Offset
  min: 0
  max: 10
  step: 0.5
  unit_of_measurement: "°F"
  initial: 2

living_room_boost_setpoint_heat_stop_threshold_offset:
  name: Living Room Boost Heat Stop Threshold Offset
  min: 0
  max: 10
  step: 0.5
  unit_of_measurement: "°F"
  initial: 1