office_heatpump_off_to_supplement_threshold:
  name: Office Heat Pump Off Temp
  min: -10
  max: 60
  step: 1
  unit_of_measurement: "째F"
  initial: 22

office_heatpump_supplement_to_comfort_threshold:
  name: Office Heat Pump Comfort Temp
  min: -10
  max: 60
  step: 1
  unit_of_measurement: "째F"
  initial: 32

office_overheated_threshold:
  name: Office Overheat Threshold
  min: 70
  max: 90
  step: 1
  unit_of_measurement: "째F"
  initial: 73

office_override_setpoint:
  name: Office Override Temperature
  min: 60
  max: 80
  step: 1
  unit_of_measurement: "째F"
  initial: 70

office_override_for_hours:
  name: Office Override For Hours
  min: 0.25
  max: 24
  step: 0.25
  unit_of_measurement: "hours"
  initial: 0.25