hvac_mini_split_off_when_unworking_temp_over_threshold_office:
  name: HVAC Office Mini Split Off When Unworking Temp Over Threshold
  min: -20
  max: 120
  step: 1
  unit_of_measurement: "°F"
  initial: 40